#!/bin/sh

command=$2

if [ "$command" = "started" ]; then
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-5,12-17
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-5,12-17
    systemctl set-property --runtime -- init.scope AllowedCPUs=0-5,12-17
elif [ "$command" = "release" ]; then
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-23
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-23
    systemctl set-property --runtime -- init.scope AllowedCPUs=0-23
fi
